from app.agents.resume.strategic.schema_assembler import create_resume_from_fragments

fragments = {
    "experiences": [],
    "skills": {"skills": [], "additional_skills": []},
    "projects": [{"id": "proj_1", "name": "Demo", "description": "desc", "url": ""}],
    "education": {"education": []},
    "contact_info": {"contact_info": []},
    "summary": "This is a plain text summary generated by the agent.",
    "name": {"name": "Test Name"}
}

final, diagnostics = create_resume_from_fragments(fragments)
print(final)
print([d.dict() for d in diagnostics])
